"""Add username to watchlist

Revision ID: 178191c64cb9
Revises: 66bc29fa78c1
Create Date: 2024-02-16 15:55:23.639649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178191c64cb9'
down_revision = '66bc29fa78c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    op.add_column('watchlist', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'username')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
