"""Add prices table

Revision ID: 465dc492b77d
Revises: 8f932db9ae2b
Create Date: 2024-02-04 23:44:24.166606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465dc492b77d'
down_revision = '8f932db9ae2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_prices_symbol'), 'prices', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_symbol'), table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
