"""Add users table

Revision ID: 66bc29fa78c1
Revises: 7afbfa0bf5e7
Create Date: 2024-02-16 14:31:49.504276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bc29fa78c1'
down_revision = '7afbfa0bf5e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_unique_constraint(None, 'top_losers', ['symbol'])
    op.create_unique_constraint(None, 'top_winners', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'top_winners', type_='unique')
    op.drop_constraint(None, 'top_losers', type_='unique')
    op.drop_table('users')
    # ### end Alembic commands ###
