"""Add notifications table

Revision ID: 74577efec413
Revises: 69f5413240d8
Create Date: 2024-02-10 19:55:21.879423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74577efec413'
down_revision = '69f5413240d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'watchlist', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlist', type_='unique')
    op.drop_table('notifications')
    # ### end Alembic commands ###
