"""Add losers and winners table

Revision ID: 7afbfa0bf5e7
Revises: 74577efec413
Create Date: 2024-02-10 23:10:27.091479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afbfa0bf5e7'
down_revision = '74577efec413'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_losers',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('change', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('top_winners',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('change', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol'),
    sa.UniqueConstraint('symbol')
    )
    op.create_unique_constraint(None, 'notifications', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_table('top_winners')
    op.drop_table('top_losers')
    # ### end Alembic commands ###
