"""Create screener ids table

Revision ID: 8f932db9ae2b
Revises: 641a4ce52063
Create Date: 2024-02-04 01:14:45.421798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f932db9ae2b'
down_revision = '641a4ce52063'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screener_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_screener_ids_id'), 'screener_ids', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screener_ids_id'), table_name='screener_ids')
    op.drop_table('screener_ids')
    # ### end Alembic commands ###
